version: '3.8'
services:
  go:
    container_name: go
    build:
      context: .
      dockerfile: ./.docker/go/Dockerfile
    volumes:
      - './:/app'
    working_dir: '/app'
    ports:
      - '8000:8000'
    env_file: .env
    networks:
      - network

networks:
  network:
    driver: bridge
