-- Run this in Supabase SQL Editor

create table if not exists public.happiness_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  age integer not null,
  happiness_score smallint not null,
  reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, age)
);

alter table public.happiness_entries
  drop constraint if exists happiness_entries_age_check;

alter table public.happiness_entries
  add constraint happiness_entries_age_check
  check (age between 0 and 30);

alter table public.happiness_entries
  drop constraint if exists happiness_entries_happiness_score_check;

alter table public.happiness_entries
  add constraint happiness_entries_happiness_score_check
  check (happiness_score between -10 and 10);

create index if not exists happiness_entries_user_age_idx
  on public.happiness_entries (user_id, age);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trigger_happiness_entries_updated_at on public.happiness_entries;
create trigger trigger_happiness_entries_updated_at
before update on public.happiness_entries
for each row execute function public.set_updated_at();

alter table public.happiness_entries enable row level security;

drop policy if exists "happiness_entries_select_own" on public.happiness_entries;
create policy "happiness_entries_select_own"
on public.happiness_entries
for select
using (auth.uid() = user_id);

drop policy if exists "happiness_entries_insert_own" on public.happiness_entries;
create policy "happiness_entries_insert_own"
on public.happiness_entries
for insert
with check (auth.uid() = user_id);

drop policy if exists "happiness_entries_update_own" on public.happiness_entries;
create policy "happiness_entries_update_own"
on public.happiness_entries
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "happiness_entries_delete_own" on public.happiness_entries;
create policy "happiness_entries_delete_own"
on public.happiness_entries
for delete
using (auth.uid() = user_id);

-- Optional: if old table remains from previous design
-- drop table if exists public.happiness_profile;
